import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { supabase } from '../utils/supabaseClient'
import { Box, Text } from '@chakra-ui/react'
import Navbar from '../components/Navbar'
import Recipe from '../components/Recipe'
import SelectedRecipesBadge from '../components/SelectedRecipesBadge'

export default function Home({ data }) {
  const [selectedRecipes, setSelectedRecipes] = React.useState([])

  const addRecipeSelectedRecipes = (recipeID) => {
    setSelectedRecipes((selectedRecipes) => [...selectedRecipes, recipeID])
  }

  const removeRecipeSelectedRecipes = (recipeID) => {
    setSelectedRecipes(
      selectedRecipes.filter(
        (selectedRecipeID) => recipeID !== selectedRecipeID
      )
    )
  }
  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <SelectedRecipesBadge recipesLength={selectedRecipes.length} />
        <Box w='full' display='flex' justifyContent='space-around'>
          {data.map((recipe) => {
            return (
              <>
                <Recipe
                  id={recipe.id}
                  name={recipe.name}
                  name_secondary={recipe.name_secondary}
                  imgurl={recipe.imgurl}
                  addRecipeSelectedRecipes={addRecipeSelectedRecipes}
                  removeRecipeSelectedRecipes={removeRecipeSelectedRecipes}
                />
              </>
            )
          })}
        </Box>
      </div>
    </>
  )
}

export async function getServerSideProps(context) {
  let { data, error } = await supabase.from('recipe').select('*')

  return {
    props: {
      data: data,
    }, // will be passed to the page component as props
  }
}
