import Head from 'next/head'
import { useEffect } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { supabase } from '../utils/supabaseClient'
import { Box, Text } from '@chakra-ui/react'
import Navbar from '../components/Navbar'
import Recipe from '../components/Recipe'

export default function Home({ data }) {
  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Box w='full' display='flex' justifyContent='space-around'>
          {data.map((recipe) => {
            return (
              <>
                <Recipe
                  id={recipe.id}
                  name={recipe.name}
                  name_secondary={recipe.name_secondary}
                  imgurl={recipe.imgurl}
                />
              </>
            )
          })}
        </Box>
      </div>
    </>
  )
}

export async function getServerSideProps(context) {
  let { data, error } = await supabase.from('recipe').select('*')

  return {
    props: {
      data: data,
    }, // will be passed to the page component as props
  }
}
